### ISSUE TITLE
appium服务端和客户端跑到两个不同机器有什么好的思路吗?

### ISSUE THREAD

**Issue by laosijizhongcai** [ztwo/Auto_Analysis#3]
现在Auto_Analysis是使用随机产生的端口号启动本地的appium服务,appium客户端拿到随机创建的端口去连接appium服务,如果appium服务和客户端分别在不同的机器,有什么好的思路实现吗?谢谢

**Comment by ztwo** [comment]
其实和appium无关，android 直接adb connect即可远程链接，实现pc与手机分离
